### ISSUE TITLE
A friendly code review of your dice game

### ISSUE THREAD

**Issue by pserwylo** [IT-Jeroen/Photo_Site#1]
Looking good!

Hope you don't mind an unsolicited code review (feel free to delete the issue if so).

The idea of manually creating DOM nodes like you have [here](https://github.com/IT-Jeroen/Photo_Site/blob/main/dicee.js#L13-L27) is great. It is very much likely that in the future, you will actually use a specific JS framework rather than managing the DOM node creation yourself (e.g. React, Angular, Vue, or perhaps some more light weight solutions), however that is by no means a sure thing. Furthermore, those who have a better understanding of how a website is constructed of DOM nodes like this will always have a better time building a mental model of how these more modern JS frameworks work under the hood, and will lead to a better appreciation of how to make them do what you want, as well as understand the performance tradeoffs.

With regard to your variable naming, none of them are strictly incorrect. However my advice would be to focus on the business problem you are trying to solve, and use names from that instead for naming. When you move to larger projects, it will become much easier to maintain, much easier for others working with you to build a colelctive understanding of the business problem you are working to solve, etc. Some examples:
* [`checkForWinner`](https://github.com/IT-Jeroen/Photo_Site/blob/4c2b2c6bad95e23df7ac9185b901fc58a4217743/dicee.js#L31) -> Perhaps `highestScore` or `highestScoreYet`.
* [`winner`](https://github.com/IT-Jeroen/Photo_Site/blob/4c2b2c6bad95e23df7ac9185b901fc58a4217743/dicee.js#L32) - `winners` helps because it is an array, but it doesn't hint at what is inside. Perhaps `winningPlayerNumbers` (though I'm famously verbose with some of my names, so don't always take my advice here).
* [`randomNumberArray`](https://github.com/IT-Jeroen/Photo_Site/blob/4c2b2c6bad95e23df7ac9185b901fc58a4217743/dicee.js#L7) - Yes, it is an array of random numbers, but what these numbers actually represent are the faces of each dice which were rolled. So perhaps `diceValues` or `dice` or `diceFaces`.

All in all, a nice little toy you've built.

**Comment by IT-Jeroen** [comment]
Variable naming convention has been changed. I also updated the script with JQuery for the creation of DOM nodes.
Thanks.

**Comment by pserwylo** [comment]
Nice, reads really well now, almost like English. The jQuery is definitely an improvement in terms of the reduced amount of code and improved code readability. The only thing I'd caution is that the first one, though very verbose, is good to keep in your mind as you make use of *any* other library (jQuery included). Under the hood, that is what they are all executing, so keeping that in the back of your mind will help to understand why these libraries exist, what problem they solve, and how they solve the problems.
